set(SOURCE_FILES
  include/angelscript-integration/angelscript-integration.h
  include/angelscript-integration/call-script.h
  include/angelscript-integration/call-script.inl
  include/angelscript-integration/change-working-dir.h
  include/angelscript-integration/implementation/function-wrapper.h
  include/angelscript-integration/ref-counted-object.h
  include/angelscript-integration/ref-counted-object.inl
  include/angelscript-integration/ref.h
  include/angelscript-integration/ref.inl
  include/angelscript-integration/weakref.h
  include/angelscript-integration/weakref.inl
  src/angelscript-integration/angelscript-integration.cpp
  src/angelscript-integration/call-script.cpp
  src/angelscript-integration/change-working-dir.cpp
  src/angelscript-integration/glm/engine-library-math-vector-classes.cpp
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators-bvec-rgba.cpp
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators-bvec-stpq.cpp
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators-bvec-xyzw.cpp
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators-dvec-rgba.cpp
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators-dvec-stpq.cpp
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators-dvec-xyzw.cpp
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators.h
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators-ivec-rgba.cpp
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators-ivec-stpq.cpp
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators-ivec-xyzw.cpp
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators-uvec-rgba.cpp
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators-uvec-stpq.cpp
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators-uvec-xyzw.cpp
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators-vec-rgba.cpp
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators-vec-stpq.cpp
  src/angelscript-integration/glm/engine-library-math-vector-swizzle-operators-vec-xyzw.cpp
  src/angelscript-integration/glm/include-glm.h
  src/angelscript-integration/ref-counted-object.cpp
)
